WebApplication22/Controllers/PopupController.cs
using Common.Menu;
using Data.Models;
using PagedList;
using System.Linq;
using System.Web.Mvc;

namespace WebApplication22.Controllers
{
    public class PopupController : Controller
    {
        TransartEntities db = new TransartEntities();
        public ActionResult Show(string PopupID, string FieldKind, int? PageNumber, int? PageSize)
        {
            int m_pagesize = PageSize ?? 10;
            int m_pagenumber = PageNumber ?? 1;
            ViewBag.PopupID = PopupID;
            ViewBag.PageNumber = m_pagenumber;
            ViewBag.PageSize = m_pagesize;
            ViewBag.FieldKind = FieldKind;

            My_Select_List mL;
            if (FieldKind == "dept")
            {
                mL = new Dept_Select_List();
            }
            else
            {
                mL = new Emp_Select_List();
            }
            IOrderedQueryable<Popup> sL = mL.GetSelectList();
            IPagedList<Popup> d = sL.ToPagedList(m_pagenumber, m_pagesize);
            //return PartialView("Show", d); 測試此法, 點選下一頁後, 會轉變成網頁畫面而非維持視窗
            return PartialView(d);
        }
        public ActionResult EmpOfDept(string PopupID, string DPNO, int? PageNumber, int? PageSize)
        {
            int m_pagesize = PageSize ?? 10;
            int m_pagenumber = PageNumber ?? 1;
            string m_dpno = DPNO == "undefined" ? "" : DPNO;
            ViewBag.PopupID = PopupID;
            ViewBag.PageNumber = m_pagenumber;
            ViewBag.PageSize = m_pagesize;
            ViewBag.DPNO = m_dpno;

            //My_Select_List mL = new Emp_Select_List(m_dpno);//受限部門代碼篩選員工
            My_Select_List mL = new Emp_Select_List();//取得所有員工
            IOrderedQueryable<Popup> sL = mL.GetSelectList();
            IPagedList<Popup> d = sL.ToPagedList(m_pagenumber, m_pagesize);
            return PartialView(d);
        }

        public ActionResult ShowList_employee(int? page_number, int? page_size)
        {
            //員工全選
            int m_page_number = page_number ?? 1;
            int m_page_size = page_size ?? 15; //對應現行系統筆數
            ViewBag.page_number = m_page_number;
            ViewBag.page_size = m_page_size;

            IOrderedQueryable<employee> w = db.employee
                                              .OrderBy(x => x.em_no);
            IPagedList z = w.ToPagedList(m_page_number, m_page_size);
            if (z.TotalItemCount > 0)
                return PartialView(z);
            else
                return HttpNotFound();
        }
    }
}

WebApplication22/Views/Popup/EmpOfDept.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Common.Menu.Popup>
@{
    int? m_PageNumber = ViewBag.PageNumber;
    int? m_PageSize = ViewBag.PageSize;
    string m_PopupID = ViewBag.PopupID;
    string m_DPNO = ViewBag.DPNO;
}

<table class="table table-bordered table-hover" cellpadding="0" cellspacing="0">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Text)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
        </tr>
    }

</table>
<div class="d-flex justify-content-center">
    @Html.PagedListPager(
        Model,
        page => Url.Action("EmpOfDept", "Popup", new { PopupID = m_PopupID,
                                 DPNO = m_DPNO,
                                 PageNumber = page,
                                 PageSize = m_PageSize
                           }
                          ),
        PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
            new PagedListRenderOptions() {
                LinkToFirstPageFormat = "<< 第一頁",
                LinkToPreviousPageFormat = "< 上一頁",
                LinkToNextPageFormat = "下一頁 >",
                LinkToLastPageFormat = "最後一頁 >>",
                DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                DisplayLinkToNextPage = PagedListDisplayMode.Always,
                DisplayLinkToLastPage = PagedListDisplayMode.Always,
                DisplayLinkToIndividualPages = false
                //PageCountAndCurrentLocationFormat = "第 {0} 頁 / 共 {1} 頁",
                //DisplayPageCountAndCurrentLocation = true,
                //ItemSliceAndTotalFormat = "第 {0} 到 {1} 項 / 共 {2} 項",
                //DisplayItemSliceAndTotal = true
            },
            new AjaxOptions() {
                HttpMethod = "GET",
                UpdateTargetId = m_PopupID,
                OnComplete = "trigger_setup('" + m_PopupID + "')"
            }
        )
    )
</div>

WebApplication22/Views/Popup/Show.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Common.Menu.Popup>
@{
    int? m_PageNumber = ViewBag.PageNumber;
    int? m_PageSize = ViewBag.PageSize;
    string m_PopupID = ViewBag.PopupID;
    string m_FieldKind = ViewBag.FieldKind;
}

<table class="table table-bordered table-hover" cellpadding="0" cellspacing="0">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Text)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
        </tr>
    }

</table>
<div class="d-flex justify-content-center">
    @Html.PagedListPager(
        Model,
        page => Url.Action("Show",
                           "Popup",
                           new { PopupID = m_PopupID,
                                 FieldKind = m_FieldKind,
                                 PageNumber = page,
                                 PageSize = m_PageSize
                           }
                          ),
        PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
            new PagedListRenderOptions() {
                LinkToFirstPageFormat = "<< 第一頁",
                LinkToPreviousPageFormat = "< 上一頁",
                LinkToNextPageFormat = "下一頁 >",
                LinkToLastPageFormat = "最後一頁 >>",
                DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                DisplayLinkToNextPage = PagedListDisplayMode.Always,
                DisplayLinkToLastPage = PagedListDisplayMode.Always,
                DisplayLinkToIndividualPages = false
                //PageCountAndCurrentLocationFormat = "第 {0} 頁 / 共 {1} 頁",
                //DisplayPageCountAndCurrentLocation = true,
                //ItemSliceAndTotalFormat = "第 {0} 到 {1} 項 / 共 {2} 項",
                //DisplayItemSliceAndTotal = true
            },
            new AjaxOptions() {
                HttpMethod = "GET",
                UpdateTargetId = m_PopupID,
                OnComplete = "trigger_setup('" + m_PopupID + "')"
            }
        )
    )
</div>

WebApplication22/Views/Popup/ShowList_employee.cshtml
@model PagedList.IPagedList<Data.Models.employee>
@using PagedList.Mvc;
@Styles.Render("~/Content/css")
<style>
    #ShowList_Table {
        width: 50%
    }

        #ShowList_Table th,
        #ShowList_Table tr,
        #ShowList_Table td {
            margin: 0;
            padding: 0;
        }
</style>
@{
    int m_page_number = ViewBag.page_number;
    int m_page_size = ViewBag.page_size;
}
<div class="d-flex justify-content-center">

    <table id="ShowList_Table" class="table table-bordered table-hover table-condensed">
        <thead class="bg-info text-left">
            <tr>
                <th>
                    員工編號
                </th>
                <th>
                    員工名稱
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr onclick='Pass("@item.em_no.Trim()", "@item.em_cname.Trim()", "@item.em_dpno.Trim()")'>
                    <td>
                        @Html.DisplayFor(modelitem => item.em_no)
                    </td>
                    <td>
                        @Html.DisplayFor(modelitem => item.em_cname)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="d-flex justify-content-center">
    @Html.PagedListPager(
      Model,
      page => Url.Action("ShowList_employee", "Popup", new
          {
              page_number = page,
          page_size = m_page_size
          }
                        ),
      new PagedListRenderOptions
      {
          LinkToFirstPageFormat = "<< 第一頁",
          LinkToPreviousPageFormat = "< 上一頁",
          LinkToNextPageFormat = "下一頁 >",
          LinkToLastPageFormat = "最後一頁 >>",
          DisplayLinkToFirstPage = PagedListDisplayMode.Always,
          DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
          DisplayLinkToNextPage = PagedListDisplayMode.Always,
          DisplayLinkToLastPage = PagedListDisplayMode.Always,
          DisplayLinkToIndividualPages = true
          //PageCountAndCurrentLocationFormat = "第 {0} 頁 / 共 {1} 頁",
          //DisplayPageCountAndCurrentLocation = true,
          //ItemSliceAndTotalFormat = "第 {0} 到 {1} 項 / 共 {2} 項",
          //DisplayItemSliceAndTotal = true
      })
</div>
<script>
    function Pass(em_no, em_cname, em_dpno) {
        window.opener.emp_update(em_no, em_cname, em_dpno);
        window.close();
    }
</script>