WebApplication22/Areas/SYS_23/Controllers/F_23N06Controller.cs
using Common.BasicLibrary;
using Common.Menu;
using Data.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication22.Areas.SYS_23.Models;

namespace WebApplication22.Areas.SYS_23.Controllers
{
    public class F_23N06Controller : Controller
    {
        //23. 系統權限管理 > N.資訊服務需求單 > 06. 資訊服務需求單部門主管審核作業
        //預設有權限的同仁才可看到此選項

        //資料庫物件
        TransartEntities db = new TransartEntities();
        Mail_F23N mail23 = new Mail_F23N();

        // GET: SYS_23/F_23N06
        public ActionResult Index()
        {
            return View();
        }

        //http://192.168.1.233:8000/MisService/mser01_q1.asp?The_dpno=094&loginID=785
        //<% = GetMisService3(Request.QueryString("loginID") ,Request.QueryString("The_dpno") ,Request.QueryString("PageNo") ,Request.QueryString("PageSize") ) %>

        //public ActionResult P_23N06_q(string loginID, string the_dpno, int? PageNumber, int? PageSize)
        public ActionResult P_23N06_q(string loginID, string loginName, string the_dpno, int? PageNumber, int? PageSize)
        {
            //參數與原程式碼不同, 新增傳入登入者名稱; 
            //原程式可直取登入者名稱, 新系統未設定, 故新增變數string loginName供重複使用

            //改寫程式碼如下
            /*
             * 
             Transart\MisService\library\MisService_wfls.asp 
             GetMisService3'=	Description: 資訊服務需求單--部門主管審核
             原查詢條件
                lsTableList = " MisService "
	            lsTableList = lsTableList & " Inner Join dbo.GetAllEmpList() A on MS_EMNO = em_no "

	            lsWhereList = " MS_POST = 1 and MS_YN = 0 "

	            IF loginID <> "" THEN
		            lsWhereList = lsWhereList & VBCrlf & " and MS_EMNO in (														"
		            lsWhereList = lsWhereList & VBCrlf & " 	select vr_emno from VerifyGroupUser Where   						"
		            lsWhereList = lsWhereList & VBCrlf & " 		vr_vpseq in (                           						"
		            lsWhereList = lsWhereList & VBCrlf & "	select vp_seq from VerifyGroup       								"
		            lsWhereList = lsWhereList & VBCrlf & "		where  vp_vdseq = 17                                           	"
		            lsWhereList = lsWhereList & VBCrlf & "			and (                                                   	"
		            lsWhereList = lsWhereList & VBCrlf & "				vp_emno = '" & loginID & "'                         	"
		            lsWhereList = lsWhereList & VBCrlf & "				OR (                                                	"
		            lsWhereList = lsWhereList & VBCrlf & "					vp_agent = '" & loginID & "'                    	"
		            lsWhereList = lsWhereList & VBCrlf & "					and vp_emno in (                                	"
		            lsWhereList = lsWhereList & VBCrlf & "						select vl_emno from [dbo].[v_NotWorkEmp]    	"
		            lsWhereList = lsWhereList & VBCrlf & "					)                                               	"
		            lsWhereList = lsWhereList & VBCrlf & "				)                                                   	"
		            lsWhereList = lsWhereList & VBCrlf & " 				OR (                                                	"
		            lsWhereList = lsWhereList & VBCrlf & "					vp_agent1 = '" & loginID & "'                   	"
		            lsWhereList = lsWhereList & VBCrlf & "						and vp_emno in (                            	"
		            lsWhereList = lsWhereList & VBCrlf & "							select vl_emno from [dbo].[v_NotWorkEmp]	"
		            lsWhereList = lsWhereList & VBCrlf & "						)                                           	"
		            lsWhereList = lsWhereList & VBCrlf & "						and vp_agent in (                           	"
		            lsWhereList = lsWhereList & VBCrlf & "							select vl_emno from [dbo].[v_NotWorkEmp]	"
		            lsWhereList = lsWhereList & VBCrlf & "						)                                           	"
		            lsWhereList = lsWhereList & VBCrlf & "					)                                               	"
		            lsWhereList = lsWhereList & VBCrlf & "			)                                                       	"

		            lsWhereList = lsWhereList & VBCrlf & " 		)                                                           	"
		            lsWhereList = lsWhereList & VBCrlf & " )                                                                	"
	            END IF

	            lsWhereList = lsWhereList & " order by MS_NO,MS_DATE1 "
             */

            //宣告變數
            string uid = ""; //登入者工號
            string uname = ""; //登入者名稱
            string dpno = ""; //登入者部門代號
            string SQL = ""; //SQL 查詢指令
            employee emp; //員工資料表

            //1. 依登入者指派可用系統權限
            Sysfunclist_Info.Get_sfl_id(this);

            //2. 設定登入者工號與部門資訊
            /*
            document.all.MS_EMNO.value = window.sysTransArtSecurity.loginID;
	        document.all.MS_NAME.value = window.sysTransArtSecurity.loginCName;
	        document.all.MS_DPNO.value = window.sysTransArtSecurity.loginDPNO;
             */
            uid = loginID?? "";

            //uid = "005";//測試用
            uname = loginName?? "";
            dpno = the_dpno??""; //如參數空值, 接收後會變null, 下方判斷dpno == null | dpno.Trim() == "")會異常
            //工號參數為空, 查找登入者資訊並更新所屬部門代碼
            if (uid == null | uid == "")
            {
                uid = (string)Session[TARGET.user_id];
                emp = db.employee.Find(uid.Trim());
                if (emp != null)
                {
                    uname = emp.em_cname.Trim();
                    dpno = emp.em_dpno.Trim();
                }
                else
                {
                    //警示使用者?
                }
            }
            else
            {
                //登入者工號參數不為空, 但部門代碼參數或登入者名稱為空時, 查找登入者資訊並更新所屬部門代碼
                if ((dpno == null | dpno.Trim() == "") | (uname == null | uname.Trim() == ""))
                {
                    emp = db.employee.Find(uid.Trim());
                    if (emp != null)
                    {
                        uname = emp.em_cname.Trim();
                        dpno = emp.em_dpno.Trim();
                    }
                    else
                    {
                        //警示使用者?
                    }
                }
            }

            //3. 設定查詢頁面分頁筆數
            int pageSize = PageSize ?? 10;//每頁筆數
            int pageNumber = PageNumber ?? 1;

            //4. 查詢網頁資料集合
            SQL = " select MisService.*, em_cname, dp_name ";
            SQL = SQL + " from MisService Inner Join dbo.GetAllEmpList() A on MS_EMNO = em_no ";
            SQL = SQL + " where MS_POST = 1 and MS_YN = 0 ";

            if (uid != null & uid != "")
            {
                SQL = SQL + " and MS_EMNO in ( ";
                SQL = SQL + "   select vr_emno from VerifyGroupUser Where ";
                SQL = SQL + "      vr_vpseq in ( ";
                SQL = SQL + "        select vp_seq from VerifyGroup ";
                SQL = SQL + "           where  vp_vdseq = 17 ";
                SQL = SQL + "             and( ";
                SQL = SQL + "                 vp_emno = '" + uid + "' ";
                SQL = SQL + "                 OR( ";
                SQL = SQL + "                   vp_agent = '" + uid + "' ";
                SQL = SQL + "                   and vp_emno in ( ";
                SQL = SQL + "                      select vl_emno from[dbo].[v_NotWorkEmp] ";
                SQL = SQL + "                   ) ";
                SQL = SQL + "                 ) ";
                SQL = SQL + "                 OR( ";
                SQL = SQL + "                   vp_agent1 = '" + uid + "' ";
                SQL = SQL + "                   and vp_emno in ( ";
                SQL = SQL + "                      select vl_emno from[dbo].[v_NotWorkEmp] ";
                SQL = SQL + "                   ) ";
                SQL = SQL + "                   and vp_agent in ( ";
                SQL = SQL + "                      select vl_emno from[dbo].[v_NotWorkEmp] ";
                SQL = SQL + "                   ) ";
                SQL = SQL + "                 ) ";
                SQL = SQL + "              ) ";
                SQL = SQL + "        ) ";
                SQL = SQL + "    ) ";

                try
                {
                    List<MisServiceManager> msr = db.Database.SqlQuery<MisServiceManager>(SQL).ToList();
                    IQueryable<MisServiceManager> msrIQ = msr.AsQueryable();

                    //4.1 將資料進行分頁, 並指定傳給前端的變數已設定分頁顯示
                    IPagedList msrPage = msrIQ.ToPagedList(pageNumber, pageSize);

                    //5. 傳遞參數
                    ViewBag.loginID = uid;
                    ViewBag.loginName = uname;
                    ViewBag.the_dpno = dpno;
                    ViewBag.PageSize = pageSize;
                    ViewBag.PageNumber = pageNumber;

                    return View(msrPage);
                }
                catch (System.Exception ex)
                {
                    TempData["message"] = "取得資訊需求單明細失敗:" + ex;
                    return View();
                }
            }
            else
            {
                return View();
            }//end of uid != null
        }

        public ActionResult MisServiceShow1(string MS_NO)
        {
            //改寫程式碼如下
            /*
             * 
             Transart\MisService\mser01_l1.asp
             MisServiceShow1'=	Description: 資訊服務需求單--內容
             */

            //宣告變數
            string selectStr = ""; // select SQL 字串
            string ms_no = ""; //接收參數

            //1. 接收參數
            ms_no = MS_NO;
            if (ms_no != null && ms_no.Trim() != "")
            {
                /*
                 * 
                lsFieldList = " * "
	            lsTableList = " MisService Left Join MisSerReject ON MS_NO = MST_MSNO "
	            lsWhereList = " MS_NO = '" & MS_NO & "' ORDER BY MS_no "
                 */

WebApplication22/Areas/SYS_23/Views/F_23N06/MisServiceShow1.cshtml
@model List<WebApplication22.Areas.SYS_23.Models.MisServiceReject>

@*
    改寫 Transart\MisService\mser01_l1.asp
    HTML設計補充: 因應內外層table長度無法對齊, 移除fieldset 區塊
*@

@{

    //連結UrlPath
    string my_URL = this.Request.Url.ToString();
    string my_controllername = this.ViewContext.RouteData.Values["controller"].ToString();
    int i = my_URL.IndexOf(my_controllername);
    string base_URL = my_URL.Remove(i);

    //接收controller 變數
    string ms_noSearch = ViewBag.ms_noSeach;

    //依不同操作類別設定Table 樣式
    //string titleWord = "資訊服務需求單--內容";

}

@*編輯後儲存結果確認*@
@if (TempData["message"] != null)
{
    <script type="text/javascript">
        var message = @Html.Raw(Json.Encode(TempData["message"]));
        alert(message);
    </script>
}
else
{
    //pass
}

<center>
    <form method="post" name="Clt_frm" id="Clt_frm" action="">
        @*Kind 請用全大寫KIND, 雖然controller 變數為Kind*@
        @if (Model == null)
        {
            @*此頁面是點擊資料列, 非輸入單號查詢, 故不存在此情況, 暫維持寫法不移除*@
            <table border=1 cellspacing=0 class=clsFiledTitleCenter bordercolor=#D7DCDD style="BORDER-COLLAPSE: collapse; width:98%">
                <tr>
                    <td height=50 colspan=3>查無此資訊服務需求單號：@ms_noSearch</td>
                </tr>
            </table>
            <input type=hidden id=KIND name=KIND value=""> @*未參照*@
            <input type=hidden id=MS_ACEMNO name=MS_ACEMNO>
            <input type=hidden id=MS_ACDATE name=MS_ACDATE>
        }
        else
        {
            <!--<table border=0 cellspacing=1 cellpadding=5 height=5 width="675px"> -->
            <table border=0 cellspacing=1 cellpadding=5 height=5 style="width:100%">
                @foreach (var item in Model)
                {
                    if (item.MST_ACBACKMEMO != null)
                    {
                        <tr>
                            <td colspan=5>
                                <table width=675 border=1 cellspacing=0 bordercolor=#D7DCDD style="BORDER-COLLAPSE:collapse;FONT-SIZE:12px;BACKGROUND-COLOR:#FFFF80;TEXT-ALIGN:center;width:100%">
                                    <tr>
                                        <td height=25 colspan=3 align=left>
                                            @*<B>　退件說明：</B><br>　" & Replace( MST_ACBACKMEMO , CHR(10) , "<br>　" ) & VBCrlf*@
                                            <B>　退件說明：</B><br>　@item.MST_ACBACKMEMO
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    }

                    <tr>
                        <td colspan=5>
                            <table border=1 cellspacing=0 class=clsFiledTitleCenter bordercolor=#D7DCDD style="BORDER-COLLAPSE: collapse;width:100%; BACKGROUND-COLOR:lightskyblue">
                                <tr>
                                    <td height=25 colspan=4 align=left>
                                        <B>　編號：</B>@item.MS_NO
                                        <input type=hidden id=MS_NO name=MS_NO value=@item.MS_NO>
                                        <input type=hidden id=KIND name=KIND value="">@*未被參照*@
                                    </td>
                                </tr>
                                <tr>
                                    <td height=25 width=130 align=left>
                                        <B>	　廠別：</B>台灣廠
                                    </td>
                                    <td height=25 width=175 align=left>
                                        <B>	　申請部門：</B>@item.MS_DPNAME
                                        <input type=hidden id=MS_DPNO name=MS_DPNO value=@item.MS_DPNO>
                                        <input type=hidden id=MS_DPNAME name=MS_DPNAME value=@item.MS_DPNAME>
                                    </td>
                                    <td height=25 width=175 align=left>
                                        <B>	　申請者：</B>
                                        <span id=say_name name=say_name>@item.MS_NAME</span>
                                        <input type=hidden id=MS_NAME name=MS_NAME value=@item.MS_NAME>
                                    </td>
                                    <td height=25 width=205 align=left>
                                        <B>	　申請日期：</B>@item.MS_DATE1.Value.ToString("yyyy/MM/dd")
                                    </td>
                                </tr>
                                <tr>
                                    <td height=25 colspan=3 align=left>
                                        <B>	　附件：</B>@item.MS_ATTACH 張
                                    </td>
                                    <td height=25 align=left>
                                        <B>	　希望完成日期：</B>@item.MS_DATE2.Value.ToString("yyyy/MM/dd")
                                    </td>
                                </tr>
                                <tr>
                                    <td height=25 colspan=4 align=left>
                                        <B>	　資訊服務主題項目：</B> @item.MS_SUBJECT
                                    </td>
                                </tr>
                                <tr>
                                    <td align=left colspan=4>
                                        <B>	　修改依據說明：</B>
                                        <br>　 @item.MS_CONTENT2
                                    </td>
                                </tr>
                                <tr>
                                    <td align=left colspan=4>
                                        <B>	　資訊服務內容：</B>
                                        <br>　 @item.MS_CONTENT1
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                }@*foreach*@
            </table>
        }@*end of Model == null)*@
    </form>
</center>

WebApplication22/Areas/SYS_23/Views/F_23N06/P_23N06_q.cshtml
@*
    改寫Transart\MisService\mser01_q1.asp
    維持HTML設計
*@

@model PagedList.IPagedList<WebApplication22.Areas.SYS_23.Models.MisServiceManager>
@using PagedList.Mvc;

@{
    ViewBag.Title = "資訊服務申請單--清單";

    //連結UrlPath
    string my_URL = this.Request.Url.ToString();
    string my_controllername = this.ViewContext.RouteData.Values["controller"].ToString();
    int i = my_URL.IndexOf(my_controllername);
    string base_URL = my_URL.Remove(i);

    //接收controller 傳送變數
    string loginID = ViewBag.loginID;
    string loginName = ViewBag.loginName;
    string the_dpno = ViewBag.the_dpno;
    int? PageSize = ViewBag.PageSize;
    int? PageNumber = ViewBag.PageNumber;

    //設定日期
    string today = DateTime.Today.ToLongDateString();

    //隱藏欄位依資料列數命名
    int dataCount = 0;
    string MS_NOstr = "";
    string MS_SUBJECTstr = "";
    string MS_EMNOstr = "";
    string MS_NAMEstr = "";
    string MS_DPNAME = "";
    string MS_CONTENTstr = "";
    string MS_CONTENT2str = "";
    string MS_POSTstr = "";
    string MS_REASONstr = "";
    string ms_date1 = "";
}

@*網頁處理結果之訊息顯示*@
@if (TempData["message"] != null)
{
    <script type="text/javascript">
        var message = @Html.Raw(Json.Encode(TempData["message"]));
        alert(message);
    </script>
}
else
{
    //pass
}
<form name="frmCtl" method="post" >
    <center>
        <table class="text-center datatableYellow" border=1 cellspacing=0 cellpadding=3 id='DataBody' style="behavior:url(../library/tablehl.htc); width:70%" hlColor='#FFFF66' slColor='#FFFF66' bordercolor='#D7DCDD'>
            <THEAD>
                <tr height=25 >
                    <td colspan=8 align="left" class='heading2'>資訊服務需求單--部門主管審核</td>
                </tr>
                <tr>
                    <td height=20 width=70 class='clsFiledTitleCenter'>單號</td>
                    <td height=20 width=150 class='clsFiledTitleCenter'>主題</td>
                    <td height=20 width=300 class='clsFiledTitleCenter'>服務內容</td>
                    <td height=20 width=60 class='clsFiledTitleCenter'>申請者</td>
                    <td height=20 width=70 class='clsFiledTitleCenter'>申請部門</td>
                    <td height=20 width=70 class='clsFiledTitleCenter'>申請日期</td>
                    <td height=20 width=40 class='clsFiledTitleCenter'>選取</td>
                    <td height=20 width=90 class='clsFiledTitleCenter'>原因說明</td>
                </tr>
            </THEAD>

            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    @*為避免勾選時, 開出資料明細視窗, showcontent 指定再特定資料欄*@
                    <tr height=25>
                        @if (item.MS_ACBACKMEMO != null & item.MS_ACBACKMEMO != "")
                        {
                            <td width=70 onclick="ShowContent('@item.MS_NO')" style='cursor:pointer;BACKGROUND-COLOR:#FF8080;'>@item.MS_NO</td>
                        }
                        else
                        {
                            <td width=70 onclick="ShowContent('@item.MS_NO')" style='cursor:pointer;'>@item.MS_NO</td>

                        }

                        <td width=150 align="left" onclick="ShowContent('@item.MS_NO')" style='cursor:pointer'>@item.MS_SUBJECT</td>
                        <!--<td width=300 class='clsListNormalLeft' style='cursor:pointer' >" & Replace(MS_CONTENT,CHR(10) ,"<br>" ) & "</td>-->
                        <td width=300 align="left" onclick="ShowContent('@item.MS_NO')" style='cursor:pointer'>@item.MS_CONTENT1</td>
                        <td width=60 onclick="ShowContent('@item.MS_NO')" style='cursor:pointer'>@item.MS_NAME</td>
                        <td width=75 onclick="ShowContent('@item.MS_NO')" style='cursor:pointer'>@item.MS_DPNAME</td>
                        <td width=70 onclick="ShowContent('@item.MS_NO')" style='cursor:pointer'>
                            @{
                                if (item.MS_DATE1 != null)
                                {
                                    ms_date1 = item.MS_DATE1.Value.ToString("yyyy/MM/dd");
                                }
                                else
                                {

                                }
                            }
                            @*顯示處理過的日期資料*@
                            @ms_date1
                            @{
                                MS_NOstr = "MS_NO" + dataCount.ToString();
                                MS_SUBJECTstr = "MS_SUBJECT" + dataCount.ToString();
                                MS_EMNOstr = "MS_EMNO" + dataCount.ToString();
                                MS_NAMEstr = "MS_NAME" + dataCount.ToString();
                                MS_DPNAME = "MS_DPNAME" + dataCount.ToString();
                                MS_CONTENTstr = "MS_CONTENT" + dataCount.ToString();
                                MS_CONTENT2str = "MS_CONTENT2" + dataCount.ToString();
                                MS_POSTstr = "MS_POST" + dataCount.ToString();
                                MS_REASONstr = "MS_REASON" + dataCount.ToString();
                            }
                            <input type='hidden' id=@MS_NOstr name=@MS_NOstr value=@item.MS_NO>
                            <input type='hidden' id=@MS_SUBJECTstr name=@MS_SUBJECTstr value=@item.MS_SUBJECT>
                            <input type='hidden' id=@MS_EMNOstr name=@MS_EMNOstr value=@item.MS_EMNO>
                            <input type='hidden' id=@MS_NAMEstr name=@MS_NAMEstr value=@item.MS_NAME>
                            <input type='hidden' id=@MS_DPNAME name=@MS_DPNAME value=@item.MS_DPNAME>
                            <input type='hidden' id=@MS_CONTENTstr name=@MS_CONTENTstr value=@item.MS_CONTENT1>
                            <input type='hidden' id=@MS_CONTENT2str name=@MS_CONTENT2str value=@item.MS_CONTENT2>
                        </td>
                        <td width=40>
                            <input type=checkbox id=@MS_POSTstr name=@MS_POSTstr value='1' style="zoom:150%">
                        </td>
                        <td width=90>
                            <input id=@MS_REASONstr name=@MS_REASONstr size=11 value='' autocomplete="off">
                        </td>
                    </tr>
                    @* 已在@foreach 無須再加@*@
                    {
                        dataCount = dataCount + 1;
                    }
                } @*//end of foreach*@                
            }@*//end of if model !=null*@
        </table>
        @*設定資料筆數*@
        <input type='hidden' name='RecCount' id='RecCount' value=@dataCount>
        @*帶入登入者資訊*@
        <input type="hidden" id="MS_EMNO" name="MS_EMNO" value=@loginID>
        <input type="hidden" id="MS_NAME" name="MS_NAME" value=@loginName>
        <input type="hidden" id="MS_DPNO" name="MS_DPNO" value=@the_dpno>
        <input type="hidden" id="MS_DATE1" name="MS_DATE1" value=@today>

        @*資料大於10筆再顯示跳頁元件*@
        @if (Model.TotalItemCount > 10) //用於判斷筆數, 此變數需與controller 定義筆數一致
        {
            <div class="d-flex justify-content-center">
                @Html.PagedListPager(
                  //(PagedList.IPagedList<Data.Models.MisService>)TempData["DataRow"],
                  Model,
                   page => Url.Action("P_23N06_q", "F_23N06", new
                   {
                       loginID = loginID,
                       loginName = loginName,
                       the_dpno = the_dpno,
                       PageNumber = page,
                       PageSize = PageSize
                   }
                                     ),
                   new PagedListRenderOptions
                   {
                       LinkToFirstPageFormat = "<< 第一頁",
                       LinkToPreviousPageFormat = "< 上一頁",
                       LinkToNextPageFormat = "下一頁 >",
                       LinkToLastPageFormat = "最後一頁 >>",
                       DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                       DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                       DisplayLinkToNextPage = PagedListDisplayMode.Always,
                       DisplayLinkToLastPage = PagedListDisplayMode.Always,
                       //DisplayLinkToIndividualPages = false,
                       //PageCountAndCurrentLocationFormat = "第 {0} 頁 / 共 {1} 頁",
                       //DisplayPageCountAndCurrentLocation = true,
                       ItemSliceAndTotalFormat = "第 {0} 到 {1} 項 / 共 {2} 項",
                       DisplayItemSliceAndTotal = true
                   })
            </div>
        }

    </center>
</form>

<script>
    $(document).ready(function () {
        //設定TopButton按鈕顯示與動作
        replaceButtonText("spl_f1", "核准");
        replaceButtonText("spl_f2", "不核准");

        //確認測試系統查詢按鈕反灰, 故作此設定
        document.getElementById("spl_qry").setAttribute("disabled", true);

        //點選"核准"
        $("#spl_f1").click(function () {
            DoF1();
        });

        //點選"不核准"
        $("#spl_f2").click(function () {
            DoF2();
        });
    });

    function ShowContent(ms_no) {
        //rptURL="mser01_l1.asp?ms_no=" + ms_no ;
        //sFeature = "status:no; center:yes; help:no; dialogWidth:800px ;dialogHeight:500px ;resizable:yes";
        //retVal = window.showModelessDialog(rptURL, null, sFeature);

        var ms_no = ms_no;
        let h = 500;
        let w = 800;
        let top = (screen.height / 2) - (h / 2);
        let left = (screen.width / 2) - (w / 2);

        window.open("/SYS_23/F_23N06/MisServiceShow1?MS_NO=" + ms_no, "myWindow",
            config = "width=" + w + ",height=" + h +
            ",left=" + left + ",top=" + top + ",toolbar=no,menubar=no," +
            "resizable=yes,status=no,location=no,scrollbars=no")
    }

    function replaceButtonText(buttonId, text) {
        if (document.getElementById) {
            var button = document.getElementById(buttonId);
            if (button) {
                if (button.childNodes[0]) {
                    button.childNodes[0].nodeValue = text;
                }
                else if (button.value) {
                    button.value = text;
                }
                else //if (button.innerHTML)
                {
                    button.innerHTML = text;
                }
            }
        }
    }

    function DoF1() {
        var i;
        var checkCount = 0;
        var postValue;
        for (i = 0; i < @dataCount; i++) {
            postValue = $("#MS_POST" + i.toString()).is(":checked");
            //alert(postValue);//true==1 false
            if (postValue) {
                checkCount = checkCount + 1;
            }
        }

        if (checkCount > 0) {
            if (confirm("確定核准選取的申請單？")) {
                //document.frmCtl.action = "library/MisService_wfls.asp?wfls_Action=wfl_MisService_Post1()";
                //document.frmCtl.submit();
                $("form").attr("action", "/SYS_23/F_23N06/wfl_MisService_Post1");
                $("form").submit();
            } else {
                //no action
            }
        } else {
            alert("尚未勾選任何資料!");
        }
    }

    function DoF2() {
        var i;
        var checkCount = 0;
        var postValue;
        for (i = 0; i < @dataCount; i++) {
            postValue = $("#MS_POST" + i.toString()).is(":checked");
            if (postValue) {
                checkCount = checkCount + 1;
            }
        }

        if (checkCount > 0) {
            if (confirm("確定不核准選取的申請單？")) {
                //document.frmCtl.action = "library/MisService_wfls.asp?wfls_Action=wfl_MisService_Post2()";
                //document.frmCtl.submit();
                $("form").attr("action", "/SYS_23/F_23N06/wfl_MisService_Post2");
                $("form").submit();
            } else {
                //window.systemButton.btnSysF2.enable(true);
            }
        } else {
            alert("尚未勾選任何資料!");
        }
    }
</script>