WebApplication22/Areas/SYS_23/Controllers/F_23N01Controller.cs
using Common.BasicLibrary;
using Common.Menu;
using Data.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication22.Areas.SYS_23.Models;

namespace WebApplication22.Areas.SYS_23.Controllers
{
    public class F_23N01Controller : Controller
    {
        //23. 系統權限管理 > N.資訊服務需求單 > 01. 資訊服務需求單建立
     
        /*
        MS_POST 狀態註記:
        0: 新資料
        1: 轉審核
        3: 資訊服務需求單審核--部門主管核准
        4: 資訊服務需求單審核--部門主管不核准
        5: 資訊服務需求單審核--資訊主管核准
        6: 資訊服務需求單審核--資訊主管不核准
        7: 退件
        8: 轉件從MisServcice > MisModify        
        9: 刪除
         */

        //資料庫物件
        TransartEntities db = new TransartEntities();
        GetList getList = new GetList();
        List<SelectListItem> dp_list;//設定部門選單 (為避免更新失敗重返網頁下拉選單值空掉)

        // GET: SYS_23/F_23N01
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult P_23N01_l(int? PageNumber, int? PageSize)
        {
            //改寫程式碼如下
            /*
             * 
             Transart\MisService\library\MisService_wfls.asp 
             GetMisService '=	Description: 資訊服務需求單--清單
             原查詢條件
             lsFieldList = " * "
	         lsTableList = " MisService "
	         lsWhereList = " MS_POST = 0 ORDER BY MS_no "
            */

            //1. 依登入者指派可用系統權限
            Sysfunclist_Info.Get_sfl_id(this);

            //2. 設定查詢頁面分頁筆數
            int pageSize = PageSize ?? 10;//每頁筆數
            int pageNumber = PageNumber ?? 1;
            

            //3. 指定初始查詢網頁資料集合
            IOrderedQueryable<MisService> mis = db.MisService.Where(s => s.MS_POST == 0).OrderBy(s => s.MS_NO);

            //4. 將資料進行分頁, 並指定傳給前端的變數已設定分頁顯示
            //IPagedList<MisService> misPage = mis.ToPagedList(pageNumber, pageSize);
             IPagedList misPage = mis.ToPagedList(pageNumber, pageSize);

            //5. 傳遞變數給前端
            ViewBag.PageSize = pageSize;
            ViewBag.PageNumber = pageNumber;


            return View(misPage);
        }

        public ActionResult P_23N01_a()
        {
            //改寫Transart\MisService\mser01_a.asp
            //Transart\MisService\library\MisService_wfls.asp 

            //宣告變數
            string uid="";//登入者資訊
            string deptInfoStr = "";//取得報修者隸屬部門字串資訊
            string[] deptInfo = new string[3];//切割部門字串資訊

            //1. 設定按鈕權限
            Sysfunclist_Info.Get_sfl_id(this);

            //2. 帶入登入者資訊做預設申請人           
            uid = (string)Session[TARGET.user_id];
            if (uid != null)
            {
                //傳入登入者資訊到前端網頁

                deptInfoStr = updateDept(uid);
                deptInfo = deptInfoStr.Split('!');
                if (deptInfo != null)
                {
                    ViewBag.emno = uid;
                    ViewBag.ename = deptInfo[0];
                    ViewBag.dpno = deptInfo[1];
                    ViewBag.dpname = deptInfo[2];

                    //設定部門選單(呼叫F23_N Model下類別取得清單)
                    ViewBag.Select_Dept = new DEPT_LIST(deptInfo[1]).dept_list;//錯誤new用法? 結果null

                    //部門清單檢查
                    if (ViewBag.Select_Dept == null)
                    {
                        dp_list = getList.deptList(deptInfo[1]);
                        if (dp_list == null | dp_list.Count == 0)
                        {
                            TempData["message"] = "部門清單匯入網頁異常, 請洽資訊!";
                        }
                        else
                        {
                            ViewBag.Select_Dept = dp_list;
                        }
                    }
                }//end of if (deptInfo != null)
            }//end of if (deptInfo != null)            
            return View();
        }

        public ActionResult P_23N01_e(string MS_NO)
        {
            /*
            * 
            Transart\MisService\library\MisService_wfls 
            MisServiceEdit'=	Description: 資訊服務需求單--編輯
            原查詢條件
            lsFieldList = " * "
            lsTableList = " MisService "
            lsWhereList = " MS_POST = 0 AND MS_NO = '" & MS_NO & "' ORDER BY MS_no "

            */

            //宣告變數
            string ms_no = "";
            string dp_no = ""; //用於查找所屬部門
            MisService MisService;

            //1. 依登入者身分指定權限
            Sysfunclist_Info.Get_sfl_id(this);

            //2. 依單號回傳需求單資訊
            ms_no = MS_NO;
            if (ms_no == null | ms_no.Trim() == "")
            {                
                //維持導致前頁, 由前頁判斷是否有資料!
                ViewBag.ms_noSeach = ms_no;
                return View();
            }
            else
            {
                MisService = db.MisService.Find(ms_no.Trim());
                if (MisService == null)
                {
                    //return HttpNotFound();
                    //維持導致前頁, 由前頁判斷是否有資料!
                    ViewBag.ms_noSeach = ms_no;
                    return View();
                }
                else
                {
                    //2.1 依需求單需求者資訊比對隸屬部門
                    dp_no = MisService.MS_DPNO;
                    ViewBag.Select_Dept = new DEPT_LIST(dp_no).dept_list;

                    //部門清單檢查
                    if (ViewBag.Select_Dept == null)
                    {
                        dp_list = getList.deptList(dp_no);
                        if (dp_list == null | dp_list.Count == 0)
                        {
                            TempData["message"] = "部門清單匯入網頁異常, 請洽資訊!";
                        }
                        else
                        {
                            ViewBag.Select_Dept = dp_list;
                        }
                    }

                    return View(MisService);
                } //end of MisService == null)
            }//end of ms_no == null)  
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        //View 未包含@Html.AntiForgeryToken(), 故出錯
        //public ActionResult wfl_MisService_insert([Bind(Include = "MS_DPNO, MS_DPNAME, MS_EMNO, MS_NAME, MS_ATTACH,  MS_DATE1, MS_DATE2, MS_SUBJECT, MS_CONTENT2, MS_CONTENT1")] MisService MisService)
        public ActionResult P_23N01_a([Bind(Include = "MS_DPNO, MS_DPNAME, MS_EMNO, MS_NAME, MS_ATTACH, MS_DATE1, MS_DATE2, MS_SUBJECT, MS_CONTENT2, MS_CONTENT1")] MisService MisService)
        {
            //改寫Transart\MisService\mser01_a.asp 點選儲存觸發以下程式
            //Transart\MisService\library\MisService_wfls.asp wfl_MisService_insert
            //接續P_23N01_a 儲存後呼叫

            //wfl_MisService_insert, 改用P_23N01_a原因:
            //當檢查有務執行return View(MisService);, 會因找不到View : Areas/SYS_23/Views/F_23N01/wfl_MisService_insert.aspx 跳錯, 
            //且畫面不會顯示錯誤訊息, 故維持使用P_23N01_a

            //1. 宣告變數
            string checkResult = "";
            string mis_no = "";
            string mis_no2 = "";

            //2. 設定部門選單 (為避免更新失敗重返網頁下拉選單值空掉)
            dp_list = new List<SelectListItem>();

            if (dp_list == null | dp_list.Count == 0)
            {
                //以下函式參數為部門代號
                dp_list = getList.deptList(MisService.MS_DPNO);
            }

            //3. 填值檢查
            //3.1 未宣告model 填值樣式, 故以下永遠valid
            if (ModelState.IsValid) 
            {
                //3.1 針對填值取出檢查是否合理
                checkResult = checkData(MisService.MS_DPNO.Trim(), MisService.MS_EMNO.Trim(), MisService.MS_ATTACH, MisService.MS_SUBJECT, MisService.MS_CONTENT1, MisService.MS_CONTENT2, MisService.MS_DATE1, MisService.MS_DATE2);
                if (checkResult != "")
                {
                    TempData["message"] = checkResult;
                    ViewBag.Select_Dept = dp_list;
                    return View(MisService);//傳入原編輯物件
                }
                else
                {
                    //4. 填值檢查通過後, 取得單號
                    // 最後參數用於檢查是否第一次取值, 如1表示取值失敗會在嘗試做一次, 否則直接回傳fail
                    mis_no = getNumber.getAutoNumber("IS", 0, true, 1);
                    if (mis_no == "fail")
                    {
                        TempData["message"] = "單號取值失敗, 請洽資訊!";
                        ViewBag.Select_Dept = dp_list;
                        return View(MisService);//傳入原編輯物件
                    }
                    else
                    {
                        //4.1 檢查單號是否已存在, 避免key 重複
                        MisService ms = db.MisService.Find(mis_no);
                        if (ms != null)
                        {
                            //再次嘗試取得單號
                            mis_no2 = getNumber.getAutoNumber("IS", 0, true, 1);
                            MisService ms2 = db.MisService.Find(mis_no);
                            if (ms2 != null)
                            {
                                TempData["message"] = "單號重複取值, 更新失敗!";
                                ViewBag.Select_Dept = dp_list;
                                return View(MisService);//傳入原編輯物件
                            }
                            else
                            {
                                mis_no = mis_no2;
                                //確認單號未重複, 繼續執行存檔動作
                            }
                        }
                        else{
                            //確認單號未重複, 繼續執行存檔動作
                        } //end of ms != null                       
                    }// end of mis_no == "fail")

                    //5. 設定指定欄位值並做存檔
                    //
                    MisService.MS_NO = mis_no;
                    MisService.MS_UPDATE = DateTime.Now;
                    MisService.MS_POST = 0;
                    MisService.MS_YN = 0;
                    MisService.MS_YN1 = 0;
                    MisService.MS_CLOSE = 0;

                    //比對測試系統與新版開發系統資料差異; 測試系統沒看到寫值, 但新增有資料後有值
                    MisService.MS_VDATE = DateTime.Now;
                    MisService.MS_VDATE1 = DateTime.Now;

WebApplication22/Areas/SYS_23/Views/F_23N01/P_23N01_l.cshtml
@*
    改寫Transart\MisService\mser01_l.asp
    維持HTML設計
*@

@model PagedList.IPagedList<Data.Models.MisService>
@using PagedList.Mvc;

@{
    ViewBag.Title = "資訊服務申請單--清單";

    //連結UrlPath
    string my_URL = this.Request.Url.ToString();
    string my_controllername = this.ViewContext.RouteData.Values["controller"].ToString();
    int i = my_URL.IndexOf(my_controllername);
    string base_URL = my_URL.Remove(i);

    int? PageSize = ViewBag.PageSize;
    int? PageNumber = ViewBag.PageNumber;
}

@*轉審核或刪除後會轉島此頁*@
@if (TempData["message"] != null)
{
    <script type="text/javascript">
        var message = @Html.Raw(Json.Encode(TempData["message"]));
        alert(message);
    </script>
}
else
{
    //pass
}

<!--<table border=0 cellspacing=0 cellpadding=0 align=center width='600'>-->
<table border=0 cellspacing=0 cellpadding=0 align=center height="5" style="width:50%">
    <tr class='heading2'>
        <!--class='heading' 字體太小, height=25 高度太低-->
        <td colspan=2>資訊服務需求單--清單</td>
        <td colspan=3 align=Right>
            單號：
            @*標題要維持高度下, input 與Button 要同時設定高度留白, 避免高度填滿*@
            <input type=text id=MS_NO name=MS_NO size=8 maxlength=8 autocomplete="off" style="height:28px; padding-top:5px;">
            <input type=button value=' 編 輯 ' onclick='DoEdit()' style="height:28px; margin-top:5px;">
        </td>
    </tr>
    <tr class='clsFiledTitleCenter'>
        <td height='20' width=70 class='clsFiledTitleCenter'>單號</td>
        <td height='20' width=310 class='clsFiledTitleCenter'>主題</td>
        <td height='20' width=60 class='clsFiledTitleCenter'>申請者</td>
        <td height='20' width=80 class='clsFiledTitleCenter'>申請部門</td>
        <td height='20' width=80 class='clsFiledTitleCenter'>申請日期</td>
    </tr>
    @if (Model != null)
    {
        <tr>
            <td colspan="5">



                <!--<table border=1 cellspacing=0 cellpadding=0 align=center width='600' style="behavior:url(../library/tablehl.htc); BORDER-COLLAPSE: collapse; width:50%" hlColor='#FFFF66' slColor='#FFFF66' bordercolor='#D7DCDD'>-->
                <table class="text-center datatableYellow" border=1 cellspacing=0 cellpadding=0 align=center style="behavior:url(../library/tablehl.htc); BORDER-COLLAPSE: collapse; width:100%" hlColor='#FFFF66' slColor='#FFFF66' bordercolor='#D7DCDD'>
                    @foreach (var item in Model)
                    {
                        <!--
                        <tr height=25 onclick="" window.location.href='mser01_e.asp?MS_no=" & MS_NO & "' "" style='cursor:hand'>
                            -->
                        <tr height=25 onclick="window.location.href='@Url.Action("P_23N01_e", "F_23N01", new { MS_NO = item.MS_NO })'" style='cursor:pointer'>
                            @{
                                var ACBACKMEMO_Str = item.MS_ACBACKMEMO;
                                if (ACBACKMEMO_Str == null | ACBACKMEMO_Str == "")
                                {
                                    <td width=70>@item.MS_NO</td>
                                }
                                else
                                {
                                    <td width=70 style='BACKGROUND-COLOR: #FF8080;'> @item.MS_NO</td>
                                }
                            }

                            <td width=310 align="left">@item.MS_SUBJECT</td>
                            <td width=60>@item.MS_NAME</td>
                            <td width=80>@item.MS_DPNAME</td>
                            <td width=80>@item.MS_DATE1.Value.ToString("yyyy/MM/dd")</td>
                        </tr>
                    }
                </table>

            </td>
        </tr>
    }
</table>
@*資料大於10筆再顯示跳頁元件*@
@if (Model.TotalItemCount > 3) //用於判斷筆數, 此變數需與controller 定義筆數一致
{
    <div class="d-flex justify-content-center">
        @Html.PagedListPager(
         //(PagedList.IPagedList<Data.Models.MisService>)TempData["DataRow"],
         Model,
          page => Url.Action("P_23N01_l", "F_23N01", new
               {
              PageNumber = page,
              PageSize = PageSize
          }
                            ),
          new PagedListRenderOptions
          {
              LinkToFirstPageFormat = "<< 第一頁",
              LinkToPreviousPageFormat = "< 上一頁",
              LinkToNextPageFormat = "下一頁 >",
              LinkToLastPageFormat = "最後一頁 >>",
              DisplayLinkToFirstPage = PagedListDisplayMode.Always,
              DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
              DisplayLinkToNextPage = PagedListDisplayMode.Always,
              DisplayLinkToLastPage = PagedListDisplayMode.Always,
              //DisplayLinkToIndividualPages = false,
              //PageCountAndCurrentLocationFormat = "第 {0} 頁 / 共 {1} 頁",
              //DisplayPageCountAndCurrentLocation = true,
              ItemSliceAndTotalFormat = "第 {0} 到 {1} 項 / 共 {2} 項",
              DisplayItemSliceAndTotal = true
          })
    </div>
}


<script>
    $(document).ready(function () {
        //設定TopButton按鈕動作
        $("#spl_add").click(function () {
            doAdd();
        });
    });

    function doAdd() {
        //UrlPath
        //alert("@base_URL" + "@my_controllername" + "/P_23N01_a");
        window.location.href = "@base_URL" + "@my_controllername" + "/P_23N01_a";
    }

    function DoEdit() {
        var MS_NO = $("#MS_NO").val();
        if (MS_NO == null | MS_NO != "") {
            window.location.href = "@base_URL" + "@my_controllername" + "/P_23N01_e?MS_NO=" + MS_NO;
        } else {
            alert("請輸入單號！");
            //以下設定滑鼠焦點, 無效
            //document.all.MS_NO.focus();
            //$("#MS_NO").focus();
            //document.getElementById("#MS_NO").focus();
        }
    }
</script>

WebApplication22/Areas/SYS_23/Views/F_23N01/ShowList_employee.cshtml
@model PagedList.IPagedList<Data.Models.employee>
@using PagedList.Mvc;
@Styles.Render("~/Content/css")
<style>
    #ShowList_Table {
        width: 50%
    }

        #ShowList_Table th,
        #ShowList_Table tr,
        #ShowList_Table td {
            margin: 0;
            padding: 0;
        }
</style>
@{
    int m_page_number = ViewBag.page_number;
    int m_page_size = ViewBag.page_size;
}
<div class="d-flex justify-content-center">

    <table id="ShowList_Table" class="table table-bordered table-hover table-condensed">
        <thead class="bg-info text-left">
            <tr>
                <th>
                    員工編號
                </th>
                <th>
                    員工名稱
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr onclick='Pass("@item.em_no.Trim()", "@item.em_cname.Trim()", "@item.em_dpno.Trim()")'>
                <td>
                    @Html.DisplayFor(modelitem => item.em_no)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.em_cname)
                </td>
                
            </tr>
            }
        </tbody>
    </table>
</div>
<div class="d-flex justify-content-center">
    @Html.PagedListPager(
      Model,
      page => Url.Action("ShowList_employee", "F_23M01", new
          {
              page_number = page,
          page_size = m_page_size
          }
                        ),
      new PagedListRenderOptions
      {
          LinkToFirstPageFormat = "<< 第一頁",
          LinkToPreviousPageFormat = "< 上一頁",
          LinkToNextPageFormat = "下一頁 >",
          LinkToLastPageFormat = "最後一頁 >>",
          DisplayLinkToFirstPage = PagedListDisplayMode.Always,
          DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
          DisplayLinkToNextPage = PagedListDisplayMode.Always,
          DisplayLinkToLastPage = PagedListDisplayMode.Always,
          DisplayLinkToIndividualPages = false
          //PageCountAndCurrentLocationFormat = "第 {0} 頁 / 共 {1} 頁",
          //DisplayPageCountAndCurrentLocation = true,
          //ItemSliceAndTotalFormat = "第 {0} 到 {1} 項 / 共 {2} 項",
          //DisplayItemSliceAndTotal = true
      })
</div>
<script>
    function Pass(em_no, em_cname, em_dpno) {
        window.opener.emp_update(em_no, em_cname, em_dpno);
        window.close();
    }
</script>